
services:
  postgres:
    image: postgres:latest
    container_name: postgres-movies
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE_DEV}
      POSTGRES_USER: ${DB_USERNAME_DEV}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEV}
    ports:
      - "${DB_PORT_DEV}:5432"
    volumes:
      - ./src/script/movies-db.sql:/docker-entrypoint-initdb.d/movies-db.sql
      - ./postgres:/data/db